server:
  port: 8086
spring:
  application:
    name: reliable-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reliable_message?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.8.189:8848
        ip: 10.33.50.40
        metadata: {"version":@version@}
      config:
        server-addr: 10.0.8.189:8848
        file-extension: yml

  kafka:
    bootstrap-servers: 10.33.80.103:9092

feign:
  hystrix:
    enabled: true #默认feign是不开启hystrix的，所以要设置该配置为true

management:
  security:
    enabled: false

info:
  version: "@project.version@"
  app:
   name: "@artifactId@"
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.reliable.message.client.server.domain  #配置别名作用（如果在mapper 中不写简称，可以不配置这个）





elastic:
  job:
    zookeeper:
      addressList: 10.33.80.103:2181
      namespace: elastic-job-${spring.application.name}
    cron:
      confirmFinishMessageClearCron: 0 0/30 * * * ? *
      waitConfirmMessageJobCron: 0 0/1 * * * ? *
      sendingMessageCron: 0 0/30 * * * ? *







